lab/urls.py
"""
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


from django.conf.urls import url
from . import views


urlpatterns = [
    # export
    url(r'^export/(?P<dialog>\w+)/$', views.export, name='export'),
    url(r'^export_at/(?P<dialog>\w+)/$', views.export_at, name='export audit trail'),
    url(r'^export/(?P<dialog>\w+)/(?P<reagent>\w+)/$', views.export_reagents, name='export reagents'),
    url(r'^export_at/(?P<dialog>\w+)/(?P<reagent>\w+)/$', views.export_reagents_at, name='export reagents audit trail'),
    # url(r'^import/(?P<dialog>\w+)/$', views.import_data, name='import'),
    # others
    url(r'^offset/$', views.offset, name='offset'),
    url(r'^sidebar/$', views.sidebar, name='sidebar'),
    # index
    url(r'^$', views.index, name='index'),
    url(r'^index/login/$', views.index_login, name='index login'),
    url(r'^index/password/$', views.index_password, name='index password'),
    url(r'^index/logout/$', views.index_logout, name='index logout'),
    # conditions
    url(r'^conditions/$', views.conditions, name='conditions'),
    url(r'^conditions/new/$', views.conditions_new, name='conditions new'),
    url(r'^conditions/edit/$', views.conditions_edit, name='conditions edit'),
    url(r'^conditions/delete/$', views.conditions_delete, name='conditions delete'),
    url(r'^conditions/audit_trail/$', views.conditions_audit_trail, name='conditions audit trail'),
    # types
    url(r'^types/$', views.types, name='types'),
    url(r'^types/new/$', views.types_new, name='types new'),
    url(r'^types/edit/$', views.types_edit, name='types edit'),
    url(r'^types/delete/$', views.types_delete, name='types delete'),
    url(r'^types/audit_trail/$', views.types_audit_trail, name='types audit trail'),
    # type attributes
    url(r'^type_attributes/$', views.type_attributes, name='type attributes'),
    url(r'^type_attributes/new/$', views.type_attributes_new, name='type attributes new'),
    url(r'^type_attributes/edit/$', views.type_attributes_edit, name='type attributes edit'),
    url(r'^type_attributes/delete/$', views.type_attributes_delete, name='type attributes delete'),
    url(r'^type_attributes/audit_trail/$', views.type_attributes_audit_trail, name='type attributes audit trail'),
    # locations
    url(r'^locations/$', views.locations, name='locations'),
    url(r'^locations/new/$', views.locations_new, name='locations new'),
    url(r'^locations/edit/$', views.locations_edit, name='locations edit'),
    url(r'^locations/delete/$', views.locations_delete, name='locations delete'),
    url(r'^locations/audit_trail/$', views.locations_audit_trail, name='locations audit trail'),
    url(r'^locations/label/$', views.locations_label, name='locations label'),
    # boxes
    url(r'^boxes/$', views.boxes, name='boxes'),
    url(r'^boxes/new/$', views.boxes_new, name='boxes new'),
    url(r'^boxes/edit/$', views.boxes_edit, name='boxes edit'),
    url(r'^boxes/delete/$', views.boxes_delete, name='boxes delete'),
    url(r'^boxes/audit_trail/$', views.boxes_audit_trail, name='boxes audit trail'),
    url(r'^boxes/label/$', views.boxes_label, name='boxes label'),
    # box types
    url(r'^box_types/$', views.box_types, name='box types'),
    url(r'^box_types/new/$', views.box_types_new, name='box types new'),
    url(r'^box_types/edit/$', views.box_types_edit, name='box types edit'),
    url(r'^box_types/delete/$', views.box_types_delete, name='box types delete'),
    url(r'^box_types/audit_trail/$', views.box_types_audit_trail, name='box types audit trail'),
    # reagents
    url(r'^reagents/new/(?P<reagent>\w+)/$', views.reagents_new, name='reagents new'),
    url(r'^reagents/edit/(?P<reagent>\w+)/$', views.reagents_edit, name='reagents edit'),
    url(r'^reagents/delete/$', views.reagents_delete, name='reagents delete'),
    url(r'^reagents/audit_trail/(?P<reagent>\w+)/$', views.reagents_audit_trail, name='reagents audit trail'),
    url(r'^reagents/label/$', views.reagents_label, name='reagents label'),
    url(r'^reagents/(?P<reagent>\w+)/$', views.reagents, name='reagents'),
    # logs
    url(r'^movement_log/$', views.movement_log, name='movement log'),
    url(r'^login_log/$', views.login_log, name='login log'),
    url(r'^label_log/$', views.label_log, name='label log'),
    url(r'^boxing_log/$', views.boxing_log, name='boxing log'),
    # roles
    url(r'^roles/$', views.roles, name='roles'),
    url(r'^roles/new/$', views.roles_new, name='roles new'),
    url(r'^roles/edit/$', views.roles_edit, name='roles edit'),
    url(r'^roles/delete/$', views.roles_delete, name='roles delete'),
    url(r'^roles/audit_trail/$', views.roles_audit_trail, name='roles audit trail'),
    # users
    url(r'^users/$', views.users, name='users'),
    url(r'^users/new/$', views.users_new, name='users new'),
    url(r'^users/edit/$', views.users_edit, name='users edit'),
    url(r'^users/password/$', views.users_password, name='users password'),
    url(r'^users/audit_trail/$', views.users_audit_trail, name='users audit trail'),
    url(r'^users/active/$', views.users_active, name='users active'),
    url(r'^users/activate/$', views.users_activate, name='users activate'),
    url(r'^users/deactivate/$', views.users_deactivate, name='users deactivate'),
    # overview
    url(r'^overview/$', views.overview, name='overview'),
    url(r'^overview/boxing/$', views.overview_boxing, name='overview boxing'),
    url(r'^overview/locate/$', views.overview_locate, name='overview locate'),
    url(r'^overview/movement/$', views.overview_movement, name='overview movement'),
    url(r'^overview/move/$', views.overview_move, name='overview move')
]

lab/models.py
"""
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


# python imports
import logging

# django imports
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db.models import Q
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned

# app imports
import lab.custom as custom

# secret key
SECRET = settings.SECRET

# define logger
log = logging.getLogger(__name__)


##########
# GLOBAL #
##########


CHECKSUM_LENGTH = 200
UNIQUE_LENGTH = 50
ACTION_LENGTH = 6
GENERATED_LENGTH = 40
LABEL_LENGTH = 50
PASSWORD_LENGTH = 128
DEFAULT = 255


class GlobalManager(models.Manager):
    def version(self, unique):
        dic = {self.unique: unique}
        return self.filter(**dic)[0].version

    def exist(self, unique):
        dic = {self.unique: unique}
        return self.filter(**dic).exists()

    def id(self, unique):
        dic = {self.unique: unique}
        return self.filter(**dic)[0].id

    def checksum(self, unique):
        dic = {self.unique: unique}
        return self.filter(**dic)[0].checksum


class GlobalAuditTrailManager(models.Manager):
    def checksum(self, unique):
        return self.filter(id=unique)[0].checksum

    @property
    def unique(self):
        return 'id'


###############
# CONDITIONS #
###############

# manager
class ConditionsManager(GlobalManager):
    @property
    def unique(self):
        return 'condition'

    def ref_check(self, unique):
        results = list()
        tmp = list()
        try:
            if Locations.objects.filter(condition=unique).exists():
                tmp.append(True)
                results.append(Locations.objects.filter(condition=unique).values_list('location', flat=True))
            if Types.objects.filter(Q(storage_condition=unique) | Q(usage_condition=unique)).exists():
                tmp.append(True)
                results.append(Types.objects.filter(Q(storage_condition=unique) | Q(usage_condition=unique)).
                               values_list('type', flat=True))
            if not custom.check_equal(tmp):
                return False
            else:
                return results
        except IndexError:
            return False


# table
class Conditions(models.Model):
    # id
    id = models.AutoField(primary_key=True)
    # custom fields
    condition = models.CharField(max_length=UNIQUE_LENGTH, unique=True)
    # system fields
    version = models.IntegerField()
    checksum = models.CharField(max_length=CHECKSUM_LENGTH)
    # manager
    objects = ConditionsManager()

    def __str__(self):
        return self.condition


# audit trail manager
class ConditionsAuditTrailManager(GlobalAuditTrailManager):
    pass


# audit trail table
class ConditionsAuditTrail(models.Model):
    # id
    id = models.AutoField(primary_key=True)
    id_ref = models.IntegerField()
    # custom fields
    condition = models.CharField(max_length=UNIQUE_LENGTH)
    # system fields
    version = models.IntegerField()
    action = models.CharField(max_length=ACTION_LENGTH)
    user = models.CharField(max_length=UNIQUE_LENGTH)
    timestamp = models.DateTimeField()
    checksum = models.CharField(max_length=CHECKSUM_LENGTH)
    # manager
    objects = ConditionsAuditTrailManager()


#############
# LOCATIONS #
#############

# manager
class LocationsManager(GlobalManager):
    @property
    def unique(self):
        return 'location'

    def condition(self, unique):
        dic = {self.unique: unique}
        return self.filter(**dic)[0].condition

    def locations_by_type(self, type):
        condition = Types.objects.storage_condition(type=type)
        if condition:
            try:
                return self.filter(condition=condition).all()
            except IndexError:
                return False
        else:
            return False

    def ref_check(self, unique):
        try:
            return self.filter(condition=unique).exists()
        except IndexError:
            return False

    def ref_items(self, unique):
        try:
            return self.filter(condition=unique).values_list(self.unique, flat=True)
        except IndexError:
            return None


# table
class Locations(models.Model):
    # id
    id = models.AutoField(primary_key=True)
    # custom fields
    location = models.CharField(max_length=GENERATED_LENGTH, unique=True)
    name = models.CharField(max_length=UNIQUE_LENGTH)
    condition = models.CharField(max_length=UNIQUE_LENGTH)
    max_boxes = models.CharField(max_length=UNIQUE_LENGTH)
    # system fields
    version = models.IntegerField()
    checksum = models.CharField(max_length=CHECKSUM_LENGTH)
    # manager
    objects = LocationsManager()

    def __str__(self):
        if self.name == '':
            _return = self.location
        else:
            _return = '{} ({})'.format(self.location, self.name)
        return _return


# audit trail manager
class LocationsAuditTrailManager(GlobalAuditTrailManager):
    pass


# audit trail table
class LocationsAuditTrail(models.Model):
    # id
    id = models.AutoField(primary_key=True)
    id_ref = models.IntegerField()
    # custom fields
    location = models.CharField(max_length=GENERATED_LENGTH)
    name = models.CharField(max_length=UNIQUE_LENGTH)
    condition = models.CharField(max_length=UNIQUE_LENGTH)
    max_boxes = models.CharField(max_length=UNIQUE_LENGTH)
    # system fields
    version = models.IntegerField()
    action = models.CharField(max_length=ACTION_LENGTH)
    user = models.CharField(max_length=UNIQUE_LENGTH)
    timestamp = models.DateTimeField()
    checksum = models.CharField(max_length=CHECKSUM_LENGTH)
    # manager
    objects = LocationsAuditTrailManager()


#########
# TYPES #
#########


AFFILIATIONS = (('Reagents', 'Reagents'),
                ('Samples', 'Samples'))


# manager
class TypesManager(GlobalManager):
    @property
    def unique(self):
        return 'type'

    @property
    def reagents(self):
        return self.filter(affiliation='Reagents')

    @property
    def samples(self):
        return self.filter(affiliation='Samples')

    def get_affiliation(self, type):
        try:
            return self.filter(type=type)[0].affiliation
        except IndexError:
            return False

    def storage_condition(self, type):
        try:
            return self.filter(type=type)[0].storage_condition
        except IndexError:
            return False

    def ref_check(self, unique):
        results = list()
        tmp = list()
        try:
            if TypeAttributes.objects.filter(type=unique).exists():
                tmp.append(True)
                results.append(TypeAttributes.objects.filter(type=unique).values_list('column', flat=True))
            if Boxes.objects.filter(type=unique).exists():
                tmp.append(True)
                results.append(Boxes.objects.filter(type=unique).values_list('box', flat=True))
            if not custom.check_equal(tmp):
                return False
            else:
                return results
        except IndexError:
            return False


# table
class Types(models.Model):
    # id
    id = models.AutoField(primary_key=True)
    # custom fields
    type = models.CharField(max_length=GENERATED_LENGTH, unique=True)
    affiliation = models.CharField(max_length=UNIQUE_LENGTH, choices=AFFILIATIONS)
    storage_condition = models.CharField(max_length=UNIQUE_LENGTH)
    usage_condition = models.CharField(max_length=UNIQUE_LENGTH)
    # system fields
    version = models.IntegerField()
    checksum = models.CharField(max_length=CHECKSUM_LENGTH)
    # manager
    objects = TypesManager()

    def __str__(self):
        return self.type


# audit trail manager
class TypesAuditTrailManager(GlobalAuditTrailManager):
    pass


# audit trail table
class TypesAuditTrail(models.Model):
    # id
    id = models.AutoField(primary_key=True)
    id_ref = models.IntegerField()
    # custom fields
    type = models.CharField(max_length=GENERATED_LENGTH)
    affiliation = models.CharField(max_length=UNIQUE_LENGTH)
    storage_condition = models.CharField(max_length=UNIQUE_LENGTH)
    usage_condition = models.CharField(max_length=UNIQUE_LENGTH)
    # system fields
    version = models.IntegerField()
    action = models.CharField(max_length=ACTION_LENGTH)
    user = models.CharField(max_length=UNIQUE_LENGTH)
    timestamp = models.DateTimeField()
    checksum = models.CharField(max_length=CHECKSUM_LENGTH)
    # manager
    objects = TypesAuditTrailManager()


###################
# TYPE ATTRIBUTES #
###################

# manager
class TypeAttributesManager(GlobalManager):
    @property
    def unique(self):
        return 'column'

    def columns_as_list(self, type):
        try:
            return list(self.filter(type=type).order_by('id').values_list('column', flat=True))
        except IndexError:
            return list()

    def all_list_exchanged(self, type):
        try:
            query = list(self.filter(type=type).order_by('id'))
            for row in query:
                if row.list_values:
                    row.list_values = row.list_values.split(',')
            return query
        except IndexError:
            return list()

lab/templates/lab/boxing.html
<!--
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script>
    $('#id_nav_btn_boxing').click(function() {
        if (!$(this).hasClass("disabled")) {
            var item = $('#id_table').find('#id_unique').find("td:first").text();
            $.ajax({
                method: "GET",
                url: "/" + "{{ content }}" + "/box/",
                data: {
                    'unique': item
                },
                dataType: 'json',
                success: function (data) {
                    if (data.response) {
                        $('#id_actual_box').val(data.data);
                        $('#id_modal_boxing').modal("show");
                    } else {
                        alert('Only samples can be boxed.')
                    }
                }
            });
        }
    });

    function boxing() {
        var new_box = $('#id_new_box').val();
        var actual_box = $('#id_actual_box').val();
        var item = $('#id_table').find('#id_unique').find("td:first").text();
        $.ajax({
            method: "POST",
            url: "/" + "{{ content }}" + "/boxing/",
            data: {
                'new_box': new_box,
                'actual_box': actual_box,
                'unique': item
            },
            dataType: 'json',
            success: function (data) {
                if (data.response) {
                    $('#id_modal_movement').modal('hide');
                    location.reload();
                } else {
                    handleError(data.errors, data.form_id);
                }
            }
        });
    }

    $("#id_submit_boxing").click( function () {
        boxing();
    });

    $('#id_modal_boxing').keydown(function(e) {
        if (e.keyCode === 13) {
            boxing();
        }
    }).on('shown.bs.modal', function () {
        $(this).find('#id_new_box').focus()
    }).on('hidden.bs.modal', function () {
        $("br").remove();
        $("small").remove(".error");
    });
</script>

lab/templates/lab/delete.html
<!--
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script>
    $('#id_nav_btn_delete').click(function() {
        if (!$(this).hasClass("disabled")) {
            var items = [];
            $('.selected').each(function() {
              items.push($(this).find(".unique").text());
            });
            if(confirm("Do you really want to delete record(s): " + items.toString() +  " ?")) {
                $.ajax({
                    method: "POST",
                    url: "/" + "{{ content }}" + "/delete/",
                    data: {
                        'items': JSON.stringify(items)
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.response) {
                            location.reload();
                        } else {
                            alert(data.message);
                        }
                    }
                });
            } else {
                return false;
            }
        }
    });
</script>

lab/templates/lab/duplicate.html
<!--
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script>
    $('#id_nav_btn_duplicate').click(function() {
        if (!$(this).hasClass("disabled")) {
            var element = $('#id_form_duplicate');
            element.trigger("reset");

            // fill fields
            var values = [];
            $('#id_table').find('#id_unique').children('.gui').each(function() {
                values.push($(this).text());
            });
            if (("{{ content }}" === "samples") || ("{{ content }}" === "boxes") || ("{{ content }}" === "locations") || ("{{ content }}" === "reagents")) {
                values.shift();
            }
            if ("{{ content }}" === "roles") {
                element.find('div').eq(0).find('input').val(values[0]);
                var permissions = values[1].split(',');
                $('.perm').val(permissions);
            } else {
                var a = 0;
                values.forEach(function (i) {
                    var element_type = element.find('div').eq(a).children().next().prop('nodeName');
                    if (element_type === "INPUT") {
                        var type = element.find('div').eq(a).find('input').attr('type');
                        if (type === "checkbox") {
                            if (i === "True") {
                                element.find('div').eq(a).find('input').prop('checked', true);
                            } else {
                                element.find('div').eq(a).find('input').prop('checked', false);
                            }
                        } else if (type === "password") {
                            element.find('div').eq(a).find('input').val('');
                        } else {
                            element.find('div').eq(a).find('input').val(i);
                        }
                    } else if (element_type === "SELECT") {
                        var manual = element.find('div').eq(a).find('select').hasClass("manual");
                        if (manual === true) {
                            element.find('div').eq(a).find('select').val(i);
                        } else {
                            element.find('div').eq(a).find('select option').each(function () {
                                if ($(this).text() === i) {
                                    element.find('div').eq(a).find('select').val($(this).val());
                                }
                            });
                        }
                    }
                    a++;
                });
            }
            $('#id_modal_duplicate').modal("show");
        }
    });

    function duplicate_record(dialog) {
        var myDomElement = document.getElementById("id_form_duplicate");
        {% for item in modal_js_get %}
            {{ item|safe }}
        {% endfor %}
        $.ajax({
            method: "POST",
            url: "/" + dialog + "/new/{% if content_dynamic %}{{ content_dynamic }}/{% endif %}",
            data: {
                {% for item in modal_js_post %}
                    {{ item|safe }}
                {% endfor %}
            },
            dataType: 'json',
            success: function (data) {
                if (data.response) {
                    $('#id_modal_duplicate').modal('hide');
                    location.reload();
                } else {
                    handleError(data.errors, "id_form_duplicate");
                }
            }
        });
    }


    $("#id_submit_duplicate").click(function () {
        duplicate_record('{{ content }}');
    });

    $('#id_modal_duplicate').keydown(function(e) {
        if (e.keyCode === 13) {
              duplicate_record('{{ content }}');
        }
    }).on('shown.bs.modal', function () {
        $(this).find('input:text').first().focus()
    }).on('hidden.bs.modal', function () {
        $("br").remove();
        $("small").remove(".error");
    });
</script>

lab/templates/lab/edit.html
<!--
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script>
    $('#id_nav_btn_edit').click(function() {
        if (!$(this).hasClass("disabled")) {
            var element = $('#id_form_edit');
            element.trigger("reset");

            // fill fields
            var values = [];
            $('#id_table').find('#id_unique').children('.gui').each(function() {
                values.push($(this).text());
            });

            if ("{{ content }}" === "roles") {
                element.find('div').eq(0).find('input').val(values[0]);
                var permissions = values[1].split(',');
                $('.perm').val(permissions);
            } else {
                var a = 0;
                values.forEach(function (i) {
                    var element_type = element.find('div').eq(a).children().next().prop('nodeName');
                    if (element_type === "INPUT") {
                        var type = element.find('div').eq(a).find('input').attr('type');
                        if (type === "checkbox") {
                            if (i === "True") {
                                element.find('div').eq(a).find('input').prop('checked', true);
                            } else {
                                element.find('div').eq(a).find('input').prop('checked', false);
                            }
                        } else if (type === "password") {
                            element.find('div').eq(a).find('input').val('');
                        } else {
                            element.find('div').eq(a).find('input').val(i);
                        }
                    } else if (element_type === "SELECT") {
                        var manual = element.find('div').eq(a).find('select').hasClass("manual");
                        if (manual === true) {
                            element.find('div').eq(a).find('select').val(i);
                        } else {
                            element.find('div').eq(a).find('select option').each(function () {
                                if ($(this).text() === i) {
                                    element.find('div').eq(a).find('select').val($(this).val());
                                }
                            });
                        }
                    }
                    a++;
                });
            }
            $('#id_modal_edit').modal("show");
        }
    });

    function edit_record(dialog) {
        var myDomElement = document.getElementById("id_form_edit");
        {% for item in modal_js_get %}
            {{ item|safe }}
        {% endfor %}
        $.ajax({
            method: "POST",
            url: "/" + dialog + "/edit/{% if content_dynamic %}{{ content_dynamic }}/{% endif %}",
            data: {
                {% for item in modal_js_post %}
                    {{ item|safe }}
                {% endfor %}
            },
            dataType: 'json',
            success: function (data) {
                if (data.response) {
                    $('#id_modal_edit').modal('hide');
                    location.reload();
                } else {
                    handleError(data.errors, data.form_id);
                }
            }
        });
    }


    $("#id_submit_edit").click(function () {
        edit_record('{{ content }}');
    });

    $('#id_modal_edit').keydown(function(e) {
        if (e.keyCode === 13) {
              edit_record('{{ content }}');
        }
    }).on('shown.bs.modal', function () {
        $(this).find('input:text').first().focus()
    }).on('hidden.bs.modal', function () {
        $("br").remove();
        $("small").remove(".error");
    });
</script>

lab/templates/lab/users_password.html
<!--
turtle-lab.org
Copyright (C) 2017  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<script>
    $('#id_nav_btn_password').click(function() {
       if (!$(this).hasClass('disabled')) {
           var v_user = $('#id_table').find('#id_unique').find("td:first").text();
           $('#id_form_password_users').trigger("reset").find('#id_user').val(v_user);
           $('#id_modal_password_users').modal('show');
        }
    });

    function setInitialPassword() {
        var myDomElement = document.getElementById("id_form_password_users");
        var v_user = $(myDomElement).find("#id_user").val();
        var v_password_new = $(myDomElement).find("#id_password_new_users").val();
        var v_password_repeat = $(myDomElement).find("#id_password_repeat_users").val();
        $.ajax({
            method: "POST",
            url: "/" + "{{ content }}" + "/password/",
            data: {
                'user': v_user,
                'password_new_users': v_password_new,
                'password_repeat_users': v_password_repeat
            },
            dataType: 'json',
            success: function (data) {
                if (!data.response) {
                    handleError(data.errors, data.form_id);
                } else {
                    location.reload();
                }
            }
        });
    }

     $("#id_submit_password_users").click(function () {
        setInitialPassword();
    });

    $('#id_modal_password_users').keydown(function(e) {
        if (e.keyCode === 13) {
              setInitialPassword();
        }
    }).on('shown.bs.modal', function () {
        $('#id_password_new_users').focus();
    }).on('hidden.bs.modal', function () {
        $("br").remove();
        $("small").remove(".error");
    });
</script>